import { Html, Head, Main, NextScript } from 'next/document';
import { name, description } from '../package.json';

export default function Document() {
  return (
    <Html>
      <Head>
        <title>{name}</title>
        <meta name={description} content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}